### ISSUE TITLE
Usage of destinations

### ISSUE THREAD

**Issue by arditzeqiraj** [SAP-samples/digital-manufacturing-extension-samples#106]
The destination is usually declared  so in the custom UI plugin extensions examples:
{
      "source": "^/external/api/(.*)$",
      "target": "$1",
      "destination": "EXTERNAL_API_DEST",
      "csrfProtection": false,
      "authenticationType": "none"
 }

The usage of the plugin itself is protected only by the CORS policy(which can be bypassed).
On the other side the destination can be easily accessed from outside. 
No policy is being accessed for protecting it. 
I see this as a lack of security and using the destinations on the custom plugins should be a no go.

A walk around would be to call the production process which calls the destination. 
The production process at least can not be called from outside without having the bearer token first.

**Comment by msaravanabhavan** [comment]
Hi Raj,

We are planning to implement authentication for securing custom content in 2405 release. If you have any further questions, please reach out to us directly through email.

Thanks and regards,
Sara
