### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by emreyolds** [SAP-samples/digital-manufacturing-extension-samples#111]
Hello,
 Me and my colleague suddenly encountered the same error today even though we didn't change anything. What could be the reason for this? Have some things changed with the DM update? We can't deploy anymore for MTA.
Thanks
![image](https://github.co
![nnew](https://github.com/SAP-samples/digital-manufacturing-extension-samples/assets/112088209/311047bb-079d-4e15-b2e5-7ae5f105c68d)
m/SAP-samples/digital-manufacturing-extension-samples/assets/112088209/f0cf2538-3e8a-494f-90c8-248a166301f3)

**Comment by kenantelyakar** [comment]
Hello Emre,
When we try clone and deploy the project which you selected (dm-coreplugin-extensions), it looks like no problem for deploying. However may your issue be based on Business Application Studio.
Can you try with local VSCode or any IDE with these commands:
-mbt build
-cf login -u <user_mail> -p <user_pass>
-cf deploy <mtar file path>

![image](https://github.com/SAP-samples/digital-manufacturing-extension-samples/assets/28999648/72ed1080-7f4b-4ea4-8614-f512eb150d86)

**Comment by panigrahyvivek** [comment]
Hi Colleagues, 

This was a temporary glitch in BAS. This should have been resolved. Anyway, the CLI commands as explained @kenantelyakar would work.

**Comment by emreyolds** [comment]
Thanks, It works! @kenantelyakar @panigrahyvivek
