### ISSUE TITLE
Side By Side Extension Deployment

### ISSUE THREAD

**Issue by senthilrits** [SAP-samples/digital-manufacturing-extension-samples#50]
Hi Experts,
Good Day. We are trying the side by side extension for one our customer as we need to store some information in custom table.  I have used your reference code that it works fine. 
However, if I try change the docker build from taranggupta1987 to ritsconsulting then it give the problem on running. Here is the error- 
 ----------------------------------------------------------------------------------
SQL Server 2019 will run as non-root by default.
This container is running as user root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
./entrypoint.sh: line 2: /opt/mssql/bin/sqlservr : No such file or directory
----------------------------------------------------------------------------------

I have tried the same on my local as well. It gives the same problem. My docker image is ritsconsulting/mssql. I have followed your instruction. Any help would be really helpful.

Regards,
Senthil.

**Comment by taranggupta1987** [comment]
Hi Senthil,

Please use the fully qualified docker image name: **ritsconsulting/ritssql:sqlcust**.

I am able to use your image and able to get the deployment success.

Thanks,
Tarang

**Comment by senthilrits** [comment]
Hi Tarang,
Thanks for your response. Yes. It working now. 
I build the docker image separately and created the database records using sql client. Then exported the image to docker hub. After that, i followed your step and it worked. 
Regards,
Senthil.

**Comment by senthilrits** [comment]
Thanks for your support Tarang.
