### ISSUE TITLE
JS Doc for POD plugin

### ISSUE THREAD

**Issue by senthilrits** [SAP-samples/digital-manufacturing-extension-samples#52]
Hi Team,
As per the document (https://github.com/SAP-samples/digital-manufacturing-extension-samples/blob/main/docs/Exercise4.2.md), we should be able to download the JS Docs. But look like, JS Docs link is changed. Right now, we are getting only the pdf. Request your help to navigate to JSDocs. Thanks in Advance.

Regards,
Senthil.

**Comment by Naxos84** [comment]
https://help.sap.com/doc/fc0bc10d54214f1d9f8c6907e58895c7/latest/en-US/2302_jsdocs_and_ExampleCustomPluginsMTA.zip

found on https://help.sap.com/docs/sap-digital-manufacturing?locale=en-US&task=develop_task
